spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: admin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect